when:
  event: [push, tag]

steps:

  load-cache:
    image: drillster/drone-volume-cache@sha256:b82e143081dfb04ba300ce7854dfcecd31e7858e1998bf89806ec74a80a78e94
    volumes: [/var/lib/docker/tmp:/cache]
    settings:
      restore: true
      mount:
        - .gradle/caches
        - .gradle/wrapper

  build:
    image: eclipse-temurin:25@sha256:c2b7ea21649875fb9052237ac4e3cd4ef63968a2a389a0a1b1a72a5e53e5c93f
    commands:
      - export GRADLE_USER_HOME=$${CI_WORKSPACE}/.gradle
      - ./gradlew build -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]
    when:
      event: push

  build-release:
    image: eclipse-temurin:25@sha256:c2b7ea21649875fb9052237ac4e3cd4ef63968a2a389a0a1b1a72a5e53e5c93f
    commands:
      - export GRADLE_USER_HOME=$${CI_WORKSPACE}/.gradle
      - ./gradlew build -Prelease=true -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]
    when:
      event: tag

  publish-snapshot:
    image: eclipse-temurin:25@sha256:c2b7ea21649875fb9052237ac4e3cd4ef63968a2a389a0a1b1a72a5e53e5c93f
    commands:
      - export GRADLE_USER_HOME=$${CI_WORKSPACE}/.gradle
      - ./gradlew publish -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]
    when:
      event: push

  publish-release:
    image: eclipse-temurin:25@sha256:c2b7ea21649875fb9052237ac4e3cd4ef63968a2a389a0a1b1a72a5e53e5c93f
    commands:
      - export GRADLE_USER_HOME=$${CI_WORKSPACE}/.gradle
      - ./gradlew publish -Prelease=true -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]
    when:
      event: tag

  save-cache:
    image: drillster/drone-volume-cache@sha256:b82e143081dfb04ba300ce7854dfcecd31e7858e1998bf89806ec74a80a78e94
    volumes: [/var/lib/docker/tmp:/cache]
    settings:
      rebuild: true
      mount:
        - .gradle/caches
        - .gradle/wrapper
